from pydantic import BaseModel, Field
from typing import List, Optional


class ResearchRequest(BaseModel):
    """
    Validation schema capturing incoming multi-tenant client requests
    to spin up a new automated agentic investigation plan.
    """
    workspace_id: str
    conversation_id: str
    query: str


class ResearchTask(BaseModel):
    """
    Represents an atomic operation unit generated by the Planner Agent
    to be assigned to a specific specialized downstream worker.
    """
    task_id: str = Field(..., description="Unique task identifier key block")
    description: str = Field(..., description="Actionable summary of what the agent must execute")
    task_type: str = Field(..., description="Target worker designation, e.g., 'retrieval', 'web_search'")
    assigned_to: Optional[str] = Field(None, description="The specific structural sub-agent name")


class ResearchPlan(BaseModel):
    """
    The master top-down execution blueprint mapping out the ordered sequence
    of granular operations necessary to synthesize the final report.
    """
    tasks: List[ResearchTask] = Field(default_factory=list, description="Ordered set of operations to resolve sequentially")


class ResearchEvidence(BaseModel):
    """
    Standardized payload format capturing raw knowledge context vectors, text blocks,
    and references harvested by individual tool agents during execution loops.
    """
    source: str = Field(..., description="Document filename tracking title or originating network URL path")
    content: str = Field(..., description="The raw uncompressed structural text excerpt or chunk details")
    evidence_type: str = Field(..., description="Silo category mapping, e.g., 'local_rag', 'web_api'")
    score: Optional[float] = Field(0.0, description="Semantic grounding relevance weight score coefficient")


class EvidenceBundle(BaseModel):
    """
    🎯 STEP 4 SCHEMAS ADDITION: Centralized multi-silo evidence collection matrix
    aggregating internal vector data slices and external live internet web assets concurrently.
    """
    internal_evidence: List[ResearchEvidence] = Field(default_factory=list, description="Context components extracted from Qdrant vector spaces")
    web_evidence: List[ResearchEvidence] = Field(default_factory=list, description="Live snippets harvested by interchangeable internet search providers")
