import json
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.db.dependencies import get_db
from app.services.hybrid_service import hybrid_search
from app.services.prompt_service import build_prompt
from app.services.retrieval_metrics import calculate_context_stats
from app.services.memory_service import get_recent_messages, save_message
from app.services.streaming_llm_service import stream_response

router = APIRouter()


class StreamRequest(BaseModel):
    conversation_id: str
    query: str


@router.post("/chat/stream")
async def stream_chat(request: StreamRequest, db: Session = Depends(get_db)):
    # 1. Pull chronological chat room history from PostgreSQL
    history = get_recent_messages(
        db=db,
        conversation_id=request.conversation_id,
        limit=10
    )

    # 2. Run multi-stage Hybrid Retrieval + Neural Cross-Encoder Reranker
    search_results = hybrid_search(request.query)

    # 3. Compress context blocks below the 8000-character budget ceiling
    prompt, used_results = build_prompt(
        query=request.query,
        search_results=search_results,
        history=history,
        max_chars=8000
    )

    # 4. Calculate metrics and format citations
    context_stats = calculate_context_stats(used_results)
    citations = []
    for result in used_results:
        citations.append({
            "source": result["metadata"]["source"],
            "page_number": result["metadata"]["page_number"],
            "chunk_index": result["metadata"]["chunk_index"],
            "rerank_score": result["rerank_score"]
        })

    # 5. Build async generator with explicitly typed JSON events
    async def event_generator():
        # First event: Emit rich citations and payload stats under the "metadata" type flag
        initial_payload = {
            "type": "metadata",
            "metrics": context_stats,
            "citations": citations
        }
        yield f"data: {json.dumps(initial_payload)}\n\n"

        full_assistant_response = ""

        # Loop through word tokens generated by Llama 3.2
        async for token in stream_response(prompt):
            full_assistant_response += token
            
            # Formatted Step 8 Event: Wrap token chunks under the explicit "token" type flag
            token_payload = {
                "type": "token",
                "content": token
            }
            yield f"data: {json.dumps(token_payload)}\n\n"

        # Final Step 8 Event: Signal the frontend client that the network stream has safely finished
        done_payload = {"type": "done"}
        yield f"data: {json.dumps(done_payload)}\n\n"

        # Save both user and assistant dialogue tracks back to PostgreSQL memory
        save_message(db=db, conversation_id=request.conversation_id, role="user", content=request.query)
        save_message(db=db, conversation_id=request.conversation_id, role="assistant", content=full_assistant_response)

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream"
    )
